# Makefile autogenerated by Dyi on 
#
# Main target: all
# Sources:  src/index.jade  src/index.ls 

.DEFAULT_GOAL := all


.PHONY: c-7oy9cqfq
c-7oy9cqfq: src/index.html 


.PHONY: p-i9x8gq0t
p-i9x8gq0t: bemified-1kwm.html 


.PHONY: r-sl2ypc9f
r-sl2ypc9f: _site/index.html 


.PHONY: c-307u3nj3
c-307u3nj3: src/index.bfd.js 


.PHONY: p-kk7rs7ix
p-kk7rs7ix: minified-o3gr.js 


.PHONY: r-dwg4c7ve
r-dwg4c7ve: _site/client.js 


.PHONY: all
all: r-sl2ypc9f r-dwg4c7ve 


.PHONY: start
start: k-1a31aopx k-pgnq3sme 


.PHONY: stop
stop: k-8jhbrlgn k-i5fcm74b 


.PHONY: prepare
prepare: src . _site 




.PHONY: k-1a31aopx
k-1a31aopx:  
	/Users/zaccaria/development/github/diy/lib/packs/../../node_modules/.bin/pm2 start /Users/zaccaria/development/github/diy/lib/packs/livereload.js -- _site/**/*


.PHONY: k-pgnq3sme
k-pgnq3sme:  
	/Users/zaccaria/development/github/diy/lib/packs/../../node_modules/.bin/pm2 start /Users/zaccaria/development/github/diy/lib/packs/serve.js -- _site -p 4000


.PHONY: k-8jhbrlgn
k-8jhbrlgn:  
	/Users/zaccaria/development/github/diy/lib/packs/../../node_modules/.bin/pm2 delete /Users/zaccaria/development/github/diy/lib/packs/livereload.js


.PHONY: k-i5fcm74b
k-i5fcm74b:  
	/Users/zaccaria/development/github/diy/lib/packs/../../node_modules/.bin/pm2 delete /Users/zaccaria/development/github/diy/lib/packs/serve.js


.PHONY: clean
clean:  
	rm -f src/index.html
	rm -f bemified-1kwm.html
	rm -f _site/index.html
	rm -f src/index.bfd.js
	rm -f minified-o3gr.js
	rm -f _site/client.js




src/index.html: src/index.jade 
	./node_modules/.bin/jade src/index.jade	

bemified-1kwm.html: src/index.html 
	./node_modules/.bin/beml-cli < src/index.html > bemified-1kwm.html	

_site/index.html: bemified-1kwm.html 
	cp bemified-1kwm.html _site/index.html	

src/index.bfd.js: src/index.ls src/less/alerts.less src/less/badges.less src/less/bootstrap.less src/less/breadcrumbs.less src/less/button-groups.less src/less/buttons.less src/less/carousel.less src/less/close.less src/less/code.less src/less/component-animations.less src/less/dropdowns.less src/less/forms.less src/less/glyphicons.less src/less/grid.less src/less/input-groups.less src/less/jumbotron.less src/less/labels.less src/less/list-group.less src/less/media.less src/less/mixins.less src/less/modals.less src/less/navbar.less src/less/navs.less src/less/normalize.less src/less/pager.less src/less/pagination.less src/less/panels.less src/less/popovers.less src/less/print.less src/less/progress-bars.less src/less/responsive-embed.less src/less/responsive-utilities.less src/less/scaffolding.less src/less/tables.less src/less/theme.less src/less/thumbnails.less src/less/tooltip.less src/less/type.less src/less/utilities.less src/less/variables.less src/less/wells.less 
	./node_modules/.bin/browserify -t liveify -t node-lessify src/index.ls -o src/index.bfd.js	

minified-o3gr.js: src/index.bfd.js 
	uglifyjs src/index.bfd.js > minified-o3gr.js	

_site/client.js: minified-o3gr.js 
	cp minified-o3gr.js _site/client.js	

src: 
	mkdir -p src	

.: 
	mkdir -p .	

_site: 
	mkdir -p _site	


